### ISSUE TITLE
Cannot read .sav file because of insufficient RAM

### ISSUE THREAD

**Issue by jandraor** [tidyverse/haven#274]
Hello everyone,

I'm doing research on education in Colombia. I'm analysing the cost of teachers' payroll. I received a file of more than 80 million rows which contains payments from 2007 to 2015. Such a file is .sav and tried to read with Haven's function "read_spss.". However, I got the following error: **cannot allocate vector of size 658.8 Mb.** I assume this happened due to my pc has no enough RAM. Is there any solution, besides buying more RAM?

SessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Operating System: Windows 10 Home 64-bit (10.0, Build 14393) (14393.rs1_release.161220-1747)
Processor: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 CPUs), ~2.6GHz
Memory: 16384MB RAM

Thanks.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.
