### ISSUE TITLE
write_sav writes generic variable name instead of actual variable name

### ISSUE THREAD

**Issue by michaelwhammer** [tidyverse/haven#295]
For some columns write_sav writes a generic variable name (V1, V2, ...) instead of the actual variable names for some variables in a data set I am working with.

Additionally (and I can make this a separate issue) I've noticed that the created .sav file is often "bloated" -
 the file size is abnormally large. If I simply open the file and do nothing but a "Save As" within SPSS the file size will shrink to 5-10 times the original size.

```
zip_file <- tempfile()
download.file("https://www.dropbox.com/s/mlxsvjas09huio2/my_data_df1.zip?dl=1", zip_file, mode = "wb")
rdata_path <- unzip(zip_file)
(load(rdata_path))

haven::write_sav(my_data_df1, "C:/TEMP/temp.sav")
```

**Comment by hadley** [comment]
I don't see any problems - when I compare `names(haven::read_sav(out_file))` to `names(my_data_df1)` I don't see any differences (except for one very long name that gets truncated)

**Comment by DJAnderson07** [comment]
Sorry, I know this issue is closed, but If I understand correctly the issue was with the SPSS file that was written out. I was having this same issue and I believe it has to do with spaces in the variable names. For example, if I run

    project_reads <- readr::read_csv("https://data.jacksonms.gov/api/views/97iy-g8hk/rows.csv")
    haven::write_sav(project_reads, "project_reads.sav")

The resulting "project_reads.sav" file has all variables names as V1:n, because all variable names are being written out with spaces in them and SPSS doesn't know how to handle that. If I change just the first name to "year" and then try again

    names(project_reads)[1] <- "year"
    haven::write_sav(project_reads, "project_reads.sav")

Then the first variable name is written out correctly, but all the rest are again V1:n. Finally, if I do something like 

    project_reads <- janitor::clean_names(project_reads)
    haven::write_sav(project_reads, "project_reads.sav")

Then all works as expected. In @michaelwhammer example, it looks to me like he had some spaces in his variable names also, which is likely why they were being written out with names like V1, V2, etc.

**Comment by michaelwhammer** [comment]
@DJAnderson07 thank you for noticing the spaces in variable names. This is likely why @hadley didn't find differences in variable names after exporting and re-importing the file I supplied - the issue is with SPSS being unable to work with variable names with spaces; `haven::write_sav` is working fine. 
Looks like I'll be calling `make.names` before `haven::write_sav` to ensure this behavior doesn't happen again. Thank you again.
