### ISSUE TITLE
haven does not support SPSS compressed (zcompressed) format file (zsav) 

### ISSUE THREAD

**Issue by allitnils** [tidyverse/haven#307]
this was opened in March 2016, and i was wondering if there has been any development?
https://github.com/tidyverse/haven/issues/153
i'm still unable to open zsav files in R. does anyone know of any plugins available, or if this is in the roadmap of haven?
Is it planned to extend abilities of haven to be able to read zsav SPSS file?

**Comment by allitnils** [comment]
@evanmiller 
@rstudio
@hadley 
@jimhester 
could someone advise/comment on the possibility of this being implemented?

**Comment by hadley** [comment]
There has not been any development. If there was it would be reported in the original issue.  Bugging us with notifications is unlikely to help.

**Comment by allitnils** [comment]
@hadley , sorry to hear you're feeling like i'm bugging you with notifications, and that your interest to help is defined by who you feel is bugging you, and who isn't?
the original request was raised 18 months ago, which is why I thought it wouldn't be out of place to ask about a status of this.

**Comment by evanmiller** [comment]
@allitnils Thanks for your interest. For questions like this, the proper etiquette is to subscribe to, comment on, or +1 an existing issue, rather than opening a duplicate issue. By opening a new issue you are creating additional work for us and cluttering our issue tracker.

There has been no progress on ZSAV, primarily due to lack of user / customer interest. Any news about ZSAV support will first be announced here: https://github.com/WizardMac/ReadStat/issues/54

**Comment by hadley** [comment]
@allitnils It's also very bad form to cc a bunch of random people that you think are involved.
