### ISSUE TITLE
Inconsistent behavior of read_dta and write_dta

### ISSUE THREAD

**Issue by tzoltak** [tidyverse/haven#337]
`write_dta()` checks if labelled variables are integers, however `read_dta()` reads such a variables as numerics. As a result:
```
x = read_dta("someFile.dta")
write_dta(x, "someOtherFile.dta")
```
throws an error: "Stata only supports labelled integers."

The most user-friendly solution would be (I think) to make `write_dta()` trying to convert labelled variables to integer by itself and throwing error only if this can't be done without lose of information.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by tzoltak** [comment]
```
x = data.frame(var = labelled(1L, c(lab = 1)))
write_dta(x, "example.dta")
y = read_dta("example.dta")
write_dta(y, "example.dta")
```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by tzoltak** [comment]
``` r
library(haven)
x = data.frame(var = labelled(1L, c(lab = 1)))
write_dta(x, "example.dta")
y = read_dta("example.dta")
write_dta(y, "example.dta")
#> Error: Stata only supports labelled integers.
#> Problems: `var`
file.remove("example.dta")
#> [1] TRUE
```

**Comment by kuriwaki** [comment]
This and #343 are the same
