### ISSUE TITLE
read_dta fails to include value labels in v1.1.1 for large files, while it works in v1.1.0

### ISSUE THREAD

**Issue by jdjohn215** [tidyverse/haven#359]
I have two .dta files. One has 800 rows and 173 variables. The other has over 38,000 rows and 1,028 variables. In haven_1.1.0 read_dta() successfully imports the value labels for each file. In haven_1.1.0, read_dta() only imports value labels for the smaller one. The larger file can still be read with the latest version of read_dta, but the value labels are lost.

I couldn't think of a good way to provide reproducible code for this issue. Sorry about that. I'll update this post if I find a large enough public .dta file to demonstrate the problem with.

**Comment by znwang25** [comment]
I have encountered the same problem. It was working under previous version.

**Comment by methodds** [comment]
I experience the same issues, something in 1.1.1 messes up the labels for Stata datasets.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by scottkosty** [comment]
@methodds Since the OP has not responded, would you by chance be willing to take the time to make a reprex so this regression could be fixed? Note that there is documentation on a reprex [here](https://www.tidyverse.org/help/) (the link in the previous comment did not work for me).

**Comment by methodds** [comment]
I'd be happy to create a regex, but unfortunately I do not have a very large Stata dataset. Nevertheless, I haven't experienced any issues with smaller ones since the last patch. @jdjohn215 could you please check again whether your large dataset leads to issues even after updating to the latest version?

**Comment by scottkosty** [comment]
Sounds good. Thanks for the quick replies you two! Just a note that I haven't come across this issue, but I use read_dta() a lot so I'm interested in keeping the ball rolling on this one. Thanks for your time on making progress on it.

**Comment by jdjohn215** [comment]
Well, I'm confused (though pleased) to say that this issue appears to be gone. I used the same file as in my original comment and tested it against v1.1.1 and v1.1.2.

Value labels appear with no problems in each case. Thanks for your continued work on the tidyverse!

**Comment by scottkosty** [comment]
@jdjohn215 well thank you for trying! @methodds can you still reproduce with the data set that you originally had experienced the issue with? @znwang25 can you still reproduce?

**Comment by methodds** [comment]
As of now I do not experience any related issues anymore! :)
