### ISSUE TITLE
Behaviour change in labelled may lead to label being zapped accidentally.

### ISSUE THREAD

**Issue by rubenarslan** [tidyverse/haven#404]
`labelled()` used to not have a `label` argument. Now for #399, it does, and it defaults to `NULL`.
So, old code that added the `label` attribute first and then added value labels, would now zap the `label`. 

Arguably, this should be mentioned in your revdep email, but I don't see a downside to making the  `label` argument default to `attr(x, 'label')` instead of `NULL`. That would replicate the previous behaviour and people probably rarely want to zap the label when assigning the `haven_labelled` class (but still could, by specifying NULL explicitly).

## Reprex
```r
library(haven)
s3 <- labelled(c(1, 1, 2), c(Male = 1, Female = 2),
               label="Assigned sex at birth")
s2 <- labelled(s3, c(Male = 1, Female = 2))
s3
s2
```

Expected output would be for `s2` to still have the `label` attribute.

**Comment by larmarange** [comment]
Dear Ruben,

it is true that the change in `haven::labelled()`, reported in `labelled` package introduce that change. 

By choice, the `labelled` package import `labelled` and `labelled_spss` functions from `haven` without changing them and then add additional functions to manipulate value and variable labels.

In the philosophy of `haven`, the purpose of `labelled()`  is mainly for creating a labelled vector when importing data. The purpose of that function is not really for recoding and/or manipulating vectors. Somehow, it is similar to functions like `data.table`, designed to create an object rather than manipulating existing objects.

In `labelled` package, more focused on data manipulation, the functions to be preferred are `var_label()`, `val_labels()` and similar functions, as presented in the vignette. They check the changes asked by the user and will add or remove the appropriate classes accordingly. 

For example:
```
> x <- c(1, 1, 2, 2)
> x
[1] 1 1 2 2
> var_label(x) <- "Variable label"
> val_labels(x) <- c(no = 1, yes = 2)
> x
<Labelled double>: Variable label
[1] 1 1 2 2

Labels:
 value label
     1    no
     2   yes
> val_labels(x) <- NULL
> x
[1] 1 1 2 2
attr(,"label")
[1] "Variable label"
> val_labels(x) <- c(no = 1, yes = 2, missing = 9)
> na_values(x) <- 9
> x
<Labelled SPSS double>
[1] 1 1 2 2
Missing values: 9

Labels:
 value   label
     1      no
     2     yes
     9 missing
> na_values(x) <- NULL
> x
<Labelled double>
[1] 1 1 2 2

Labels:
 value   label
     1      no
     2     yes
     9 missing
```

**Comment by hadley** [comment]
`labelled()` is a constructor, so I think it would be strange for it take an argument from an attribute.

**Comment by rubenarslan** [comment]
@hadley I have no intuitions about what's weird in constructors, but maybe you could still mention it in the news as another breaking change from 1->2? Just so it doesn't trip others up like me.

**Comment by hadley** [comment]
Unfortunately, I don't think it's a break change because you were using `labelled()` for off-label purposes.
