### ISSUE TITLE
write_xpt() gives confusing error for invalid dataset names

### ISSUE THREAD

**Issue by ajdamico** [tidyverse/haven#408]
line to reproduce:

	haven::write_xpt( mtcars , paste0( tempfile() , " space.sas7bdat" ) )

the " " in the filepath causes the error, but the writing failure message incorrectly says there's a column name problem

	Error in write_xpt_(data, normalizePath(path, mustWork = FALSE), version = version,  : 
	  Writing failure: A provided column name contains an illegal character (must be a letter, number, or underscore).

thanks!

**Comment by hadley** [comment]
@evanmiller I think this is a readstat buglet?

**Comment by evanmiller** [comment]
@hadley ReadStat doesn't really mess with file paths, and these are probably just passed to haven's IO callbacks anyway.

Maybe the error codes / headers got out of sync? Illegal character errors are only returned in a few places.

**Comment by hadley** [comment]
I'm pretty sure the headers have to be in sync because every time I update I delete the previous import, and re-download from github master. But I added the err number to the error message just to double check:

``` r
haven::write_xpt(mtcars, " temp.xpt")
#> Error in write_xpt_(data, normalizePath(path, mustWork = FALSE), version = version, : Writing failure: A provided column name contains an illegal character (must be a letter, number, or underscore) [26].
```

And that indeed seems to be correct.

Interestingly, I don't see the error with `write_sav()`:

``` r
haven::write_sav(mtcars, " temp.sav")
```

And that reveals the problem: `write_xpt()` constructs the dataset name from the path, in this case yielding an invalid name. 

The root cause of this problem is that I have my own implementation of `validate_xpt_name()` which is clearly much simpler than `sas_validate_name()`. Could you imagine exporting `sas_validate_name()` so I could use directly in order to give better errors from R?

**Comment by evanmiller** [comment]
Ah, that makes sense. I'll have to think about the right validation API, since the validation constraints often depend on the exact file format version being written.

**Comment by evanmiller** [comment]
Okay, I've added some new functions to help narrow down these issues on the client side:

```
readstat_error_t readstat_validate_metadata(readstat_writer_t *writer);
readstat_error_t readstat_validate_variable(readstat_writer_t *writer, const readstat_variable_t *variable);
```

These need to be called after `readstat_begin_writing_xport`.

`readstat_validate_metadata` will turn up any issues with the dataset name, file format version, or requested compression scheme.

`readstat_validate_variable` will turn up any issues with illegal variable names.

**Comment by hadley** [comment]
Thanks @evanmiller!
