### ISSUE TITLE
read_por: imports incorrect values

### ISSUE THREAD

**Issue by JanMarvin** [tidyverse/haven#413]
While writing my own spss file reader I came across a bug in haven or ReadStat. See the attached example. The example shows only a single value, there are several others in the file (checked with foreign, spss, pspp and my package as well).

```{R}
library(haven)

fl <- tempfile()
url <- "http://janda.org/c10/data%20sets/World/world-95.por"
download.file(url, fl)

df_h <- read_por(fl)

# example there are other differences in this file
df_h$POPULATN[df_h$COUNTRY == "Brazil"] # is 17400 should be 156600
```
![haven_bug](https://user-images.githubusercontent.com/1645626/48303698-a592d880-e50d-11e8-9872-257e04e80fd4.png)

**Comment by evanmiller** [comment]
Welp. It looks like ReadStat was using base-10 for the exponent part instead of base-30. Since the exponent was 2 for this particular value, that explains why the result was off by a factor of 9 (30^2/10^2). The tests weren't catching it because ReadStat is lazy and never emits an exponent, just a long mantissa. I'll get this fixed ASAP.
