### ISSUE TITLE
Are there any plans to be able to import/export Alteryx databases?

### ISSUE THREAD

**Issue by kieroneil** [tidyverse/haven#434]
My company uses Alteryx for most data manipulation and R for detailed analysis.  It would be nice to be able to be able to pull that data directly from Alteryx's native format.  
Exporting to a Tableau native format would also be a good addition.

**Comment by batpigandme** [comment]
Since haven wraps ReadStat, which only supports Stata, SAS, and SPSS, I think that would be out of scope for haven. 
Knowing nothing about Alteryx itself, there is one package that might be of interest: https://cran.r-project.org/web/packages/alterryx/index.html

You might ask over on community.rstudio.com for pointers from others working with Alteryx, Tableau, and R together.
