### ISSUE TITLE
More informative error message for illegal characters in names in write_dta

### ISSUE THREAD

**Issue by steffen-stell** [tidyverse/haven#463]
I tried to export a dataset into dta, but received the error message below. I have no experience in Stata and so it took me a bit to find out that in Stata variable names must not contain ".". It would have been much more helpful if the error message actually told you what the illegal character is that you need to replace.

`Error in write_dta_(data, normalizePath(path, mustWork = FALSE), version = stata_file_format(version)) : 
  Writing failure: A provided name contains an illegal character.`

**Comment by batpigandme** [comment]
FWIW, the error message is a "translation" of one of the ReadStat errors:
https://github.com/tidyverse/haven/blob/bf41e9eeecc147f373c7cf2a8a5c94b4170ca205/src/readstat/readstat_error.c#L80-L84
(in ReadStat [here](https://github.com/WizardMac/ReadStat/blob/1f7a3bdc3f173b914a942cde12cbb0a67baa60c7/src/readstat_error.c)).

So, it might make more sense to have any changes be upstream (i.e. benefit both ReadStat _and_ haven).

**Comment by hadley** [comment]
@evanmiller is this something you'd consider? Or is it not worth it, given the challenges of generating strings in C?

**Comment by evanmiller** [comment]
@hadley We could certainly provide more detailed information via the error handler callback.

**Comment by Shelmith-Kariuki** [comment]
Following on this issue, I also got an error while trying to save the data as .sav. It turns out that illegal characters are more than just a "." .  Illegal characters include spaces, hyphens, apostrophes, and square brackets. This line worked for me, after spending three hours debugging the code. Maybe a better error message would have helped, something like "check if your variable names include a white space, hyphen, apostrophe, square bracket, etc"

![image](https://user-images.githubusercontent.com/37449624/69495072-f7698f00-0ed3-11ea-8738-5f4c3d6e9b1f.png)

**Comment by hadley** [comment]
Minimal reprex:

``` r
df <- data.frame(.x = 1)
haven::write_dta(df, tempfile())
#> Error: Writing failure: A provided name contains an illegal character.
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hadley** [comment]
New error:

``` r
df <- data.frame(.x = 1)
haven::write_dta(df, tempfile())
#> Error: Failed to create column `.x`: A provided name contains an illegal character.
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
