### ISSUE TITLE
na.strings should be added

### ISSUE THREAD

**Issue by Jagadeeshkb** [tidyverse/haven#506]
```r
read_sas('###.sas7bdat',na.stringsc("","NA"))
```
Getting the error:
Error in read_sas("adsl.sas7bdat", na.strings = c("", "NA")) : 
  unused argument (na.strings = c("", "NA"))

While importing the file the empty string Should be taken as "NA"

**Comment by hadley** [comment]
I'm not sure what you're asking for, but it doesn't make sense to convert arbitrary strings to NA when importing from a SAS dataset as SAS has it's own way of recording missing values.

**Comment by gorcha** [comment]
Hey @Olivia-E-F, as Hadley mentioned above this isn't really appropriate for SAS, SPSS etc. files. The reason there's a separate option in `read.csv()` and friends is that text files don't have a native representation of missing data, so the argument is there to allow users to specify the conventions used in the file. This isn't relevant for the file types dealt with by haven since they already have a way of natively recording missing data that can be mapped to R's represntation of missing values.

Where there are data entry errors there are a few ways to easily perform this kind of cleaning after loading the file, for e.g. using [`dplyr::na_if()`](https://dplyr.tidyverse.org/reference/na_if.html):
```r
starwars %>%
   mutate(across(where(is.character), ~na_if(., "unknown")))
```
