### ISSUE TITLE
Can't subscript with results of na.omit

### ISSUE THREAD

**Issue by tslumley** [tidyverse/haven#530]
The `haven_labelled` and `haven_labelled_spss` classes cannot be subscripted using the results of na.action.  This has been a problem with the survey package, but I expect there will be other use cases; this is not an idiom I thought up.

In the example below, I create a minimal data frame with one variable, produce a model frame, and then try to subscript the original data frame using the `na.action` attribute of the model frame.  Normally there would be more variables, but this is minimal. 

```r
library(haven)
df <- data.frame(x1 = labelled_spss(1:10, c(Good = 1, Bad = 8), na_values = c(9, 10)))

mf <- model.frame(~x1, na.action=na.omit)
naa<-attr(mf,"na.action")

if(!is.null(naa)) mf[-naa,]
```
The error message is

```
Error: Must subset elements with a valid subscript vector.
✖ Subscript has the wrong type `omit`.
ℹ It must be logical, numeric, or character.
Run `rlang::last_error()` to see where the error occurred.
```
and the class of the output of `na.omit` is indeed `omit`.

**Comment by hadley** [comment]
Minimal reprex:

``` r
x <- na.omit(c(1:5, NA))
y <- attr(x, "na.action")

x[y]
#> [1] NA
vctrs::vec_slice(x, y)
#> Error: Must subset elements with a valid subscript vector.
#> x Subscript has the wrong type `omit`.
#> ℹ It must be logical, numeric, or character.
```

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'll move this to vctrs. I think we'd say that the class should be `c("omit", "integer")` to indicate that this object can be used as an integer vector, but we'll obviously need to work around this since this is a long standing existing behaviour.
