### ISSUE TITLE
haven::read_dta can't deal with chinese charactor correctly sometimes

### ISSUE THREAD

**Issue by iamforerunner** [tidyverse/haven#564]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
library(reprex)
library(tidyverse)

tmp = haven::read_dta('D:/sample.dta')
```

some columns are OK, but some columns are wrong with many NAs, in raw STATA dta file, they are chinese charactors.
file encoding are all translated to 'utf-8'

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
Hmm, probably fixed in dev version with latest ReadStat.
