### ISSUE TITLE
missing values for haven_labelled

### ISSUE THREAD

**Issue by dusadrian** [tidyverse/haven#573]
When missing values are defined, the result is an object of class `haven_labelled_spss`.
Is there a particular reason not to allow the same thing in a `haven_labelled` object?

SPSS is not the only software that defines missing values, which is the main reason why tagged NA values were introduced. The question is: why would a Stata user be forced to use an `_spss`-type object?

`haven_labelled` seems just fine, it only lacks an additional `is.na.haven_labelled` extension, as far as I can see.

**Comment by gorcha** [comment]
Hey! Not a haven maintainer (occasional contributor :slightly_smiling_face:) so take this with a grain of salt, but I believe they're treated differently because the SPSS "user defined missing values" are qualitatively different to tagged NAs in Stata and SAS.

* In SPSS, there are system missing values (equivalent to NA) and user missing values, which are otherwise valid values that have been flagged as missing data. Data points have a value, that is then tagged as missing.

* In Stata and SAS it's the other way around - rather than a valid value that is flagged as missing data, these are stored as normal missing data but with an extra bit to tag the kind of missingness. Data points are missing, but then an extra piece of information about the type of missing data.

Although they solve almost the same problem, they're not really compatible ways of approaching it. `na_values` and `na_range` don't really make sense in Stata and SAS, since tagged NAs are not attached to an otherwise valid code that could be specified in either `na_values` and `na_range`.

Here's an example from NORC at the University of Chicago’s 2018 [General Society Survey](https://gss.norc.org/Get-The-Data).
```r
# SPSS
head(gss_sps$HEALTH)
#> <labelled_spss<double>[6]>: Condition of health
#> [1] 2 1 0 0 1 2
#> Missing values: 0, 8, 9
#> 
#> Labels:
#>  value     label
#>      0       IAP
#>      1 EXCELLENT
#>      2      GOOD
#>      3      FAIR
#>      4      POOR
#>      8        DK
#>      9        NA

# Stata
head(gss_dta$HEALTH)
#> <labelled<double>[6]>: condition of health
#> [1]     2     1 NA(i) NA(i)     1     2
#> 
#> Labels:
#>  value     label
#>      1 excellent
#>      2      good
#>      3      fair
#>      4      poor
#>  NA(d)        DK
#>  NA(i)       IAP
#>  NA(n)        NA
```

**Comment by larmarange** [comment]
It could be relevant to be more strict in the definition of `labelled_spss()` and to forbid the use of proper `NA` or tagged NAs in the option `na_values` and `na_range`. cf. #574

**Comment by gorcha** [comment]
Yeah agreed, and it should probably limit `na_values` to length 3 in line with the restriction inside SPSS

**Comment by dusadrian** [comment]
@hadley Thanks for confirming, I started to teach this stuff to a social science class and it was driving everyone crazy. A bit more relaxed now, knowing this will eventually get fixed.

@larmarange and @gorcha: I am starting to see your points, and naturally agree it is pointless to declare tagged NA values as missing, since they are missing values anyways. If this would documented then objects of class `haven_labelled_spss` do have a purpose.

The only remaining question is: how to export a dataset containing tagged NAs to a CSV file?
(and import it back?)

This is important for long term preservation, where datasets are **not** stored in binary form, but in plain text. Metadata is saved as a separate XML file using a standard called DDI - Data Documentation Initiative.

**Comment by gorcha** [comment]
Tagged missing values don't really work for storage in a CSV.

The SPSS approach is more in line with the DDI standard (where the missingness of a value is tagged in the category metadata). A great description of the issue is on this [SPSS troubleshooting page](https://www.ibm.com/support/pages/can-spss-save-user-defined-missing-values-sas-special-missing-values) (emphasis mine)
> A lot of the problem is that SAS treats such user-missing data as "special" missing data and **actually stores it as modified data values instead of meta-data** -- data dictionary information -- the way SPSS does

I think the only way to get your data into the right format for this would be to manually recode tagged NA values to a code like so:
```r
x <- labelled(c(1, 1, tagged_na("a")))
x
#> <labelled<double>[3]>
#> [1]     1     1 NA(a)

x[is_tagged_na(x, "a")] <- 2
x
#> <labelled<double>[3]>
#> [1] 1 1 2
```

**Comment by dusadrian** [comment]
Agreed. 
And if tagged NAs consistently have the same label across all variables, this type of recoding could be performed on the whole dataset at once.

Incidentally, I've tested the way Stata exports CSV files: it uses the code ".a" in the text file.
This is interesting and I wonder if some `read_csv` function could be persuaded to interpret the character ".a" as a tagged NA.

Another interesting question: when exporting a dataset containing tagged NA values to Stata, would Stata recognise the exported NA(a) as .a?

(this is probably a relevant question for @evanmiller, too)

**Comment by gorcha** [comment]
I think it's too domain specific to really be in scope for a regular `read_csv()` style function.
I think the the best/easiest approach would be to write a wrapper function that checks any character variables to see if they conform to the pattern (e.g. all values can either be converted to doubles or match an appropriate regex and convert).

It doesn't look like `write_dta()` or `write_sas()` currently support writing out tagged NAs, but I'm 99% sure that readstat supports this and it's just not implemented in haven.
