### ISSUE TITLE
possible error on Haven help page

### ISSUE THREAD

**Issue by xmatic** [tidyverse/haven#588]
The page: https://haven.tidyverse.org/articles/semantics.html

I suspect the answer here should be 5.5, not 14:

![haven](https://user-images.githubusercontent.com/5103936/114466617-f529d280-9ba5-11eb-8fe3-c1eb1a59d73e.jpg)

**Comment by dusadrian** [comment]
This is what we would all expect, but unfortunately this is not the case.
The value 99 in the labelled vector `x1` is still a real value, even though we had declared it as a missing value. It is counter-intuitive, but this is how R works.

It **could** be made to work "as we would expect" (see for instance https://github.com/tidyverse/haven/issues/574#issuecomment-817035252), but that is apparently not the formal philosophy adopted by package `haven`.

For the moment, in order to get 5.5 as a result, you need to write:
```r
library(haven)
library(labelled)
x1 <- labelled_spss(c(1:10, 99), c(Missing = 99), na_value = 99)

mean(user_na_to_na(x1), na.rm = TRUE)
# [1] 5.5
```

This is rather ugly for my taste, but that's how the way it is.

**Comment by xmatic** [comment]
@dusadrian 

Thank you for your help. Your answer works. (Note to self: the "labelled" package (a haven "helper" package) needs to be installed for it to work.)

@dusadrian I just wanted to let you know that I found that `zap_missing(x)`, [described here](https://haven.tidyverse.org/reference/zap_missing.html), also works to convert all user defined SPSS missing-values to R-style "NA".

**Comment by dusadrian** [comment]
Glad it helps, @xmatic 
Perhaps another interesting note, the new package "declared" deals with missing values out of the box:
```{r}
library(declared)
x1 <- declared(c(1:10, 99), c(Missing = 99), na_value = 99)
mean(x1)
# [1] 5.5
```
