### ISSUE TITLE
R Session Abort caused by read_dta

### ISSUE THREAD

**Issue by micsky** [tidyverse/haven#594]
I was working with a r script, which I have already written several weeks ago and everything was working just fine. Today I wanted to read in a .dta file and suddendly every time I am trying to us the ````read_dta```` function to do so the session crashes. A collegue of mine is experiencing the same problem as well as another person from stackoverflow (see my question on stackoverflow - https://stackoverflow.com/questions/67288533/am-i-the-only-one-experiencing-problems-with-rs-haven-package?answertab=votes#tab-top ).

I am using haven version 2.4.1, R 4.0.5. on Windows 10 x64 (build 19042).

```r
# code which was working fine until now
install.packages("haven")
library(haven)
my_data <- read_dta("my_path_structure\\file_name.dta")

# provoked R console feedback
*** caught segfault ***
address 0x0, cause 'invalid permissions'
```

**Comment by brhkim** [comment]
Hi! I just had this exact same issue, but I was finding it completely dependent on the underlying dataset I was loading in. I did some trial-and-error and found that the root cause was a couple of variables stored as type `strL`. Converting those variables to `str#`'s in Stata before saving resolved the issue while loading into R via Haven. Not sure if this will apply broadly, but that's how it worked for me.

**Comment by micsky** [comment]
@brhkim Hey. Oh, that's an interesting point! Think I will try this myself.
