### ISSUE TITLE
Error: Failed to parse SAS dataset 

### ISSUE THREAD

**Issue by psrwat** [tidyverse/haven#607]
Hi ,

I am getting issue while importing sas data in R using haven.

Error: Failed to parse "SAS dataset" Invalid file, or file has unsupported features.

Thanks
PSR

**Comment by AntonShemiakin** [comment]
Hi psrwat,

Can you please clarify: do you try to download SAS dataset initially created on SAS or on R ?

Regards,
Anton

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by AntonShemiakin** [comment]
Hi Hadley, 

Sorry for my long absence, I had so busy days at my work. I will provide you with reprex within next two days! 

Also, I will provide with reprex regarding label’s disappear for the specific case, if you remember it was also me who had written you an e-mail about this issue.

Sent from my iPhone,
Anton

**Comment by AntonShemiakin** [comment]
Add Hadley to the loop

Sent from my iPhone, 
Anton

**Comment by psrwat** [comment]
Hi,
Dataset which I was trying to import was created on sas viya v.03.5. I will recreate and get back to you on this soon with Code and data.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
