### ISSUE TITLE
read_sas shows output of missing columns

### ISSUE THREAD

**Issue by mzhaider** [tidyverse/haven#679]
brief details

I am trying to open some sas files using read_sas but don't want the console to show which variables are completely missing. Right now it shows a list of variable with complete missing cases

**Comment by gorcha** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
