### ISSUE TITLE
Compiler errors when using LLVM cxx17 in src/DfWriter.cpp

### ISSUE THREAD

**Issue by michaelquinn32** [tidyverse/haven#688]
We're currently in the process of updating our tool chain to use cxx17 in LLVM. As a part of this update, we have a custom static_assert that makes sure `std::hash<const char*>` doesn't occurm since it's very likely a bug. 

```
cxx17/functional:26:5: error: static_assert failed due to requirement 'sizeof (t) < 0' "hash<const char*> would hash 
  the pointer, not the contents of the string, which is almost certainly not what you want. To explicitly hash the pointers, 
  use const void*."
    static_assert(sizeof(t) < 0,

haven/src/DfWriter.cpp:76:3: note: in instantiation of member function 'std::unordered_map<const char *, readstat_string_ref_s *>::unordered_map' requested here
  Writer(FileExt ext, cpp11::list x, cpp11::strings pathEnc): ext_(ext), vendor_(extVendor(ext)), version_(0), x_(x) {
``` 

According to a colleague, the issue is that `std::unordered_map<const char*, T>` hashes `const char*`. People likely expect that it hashes the string the pointer points to, but it just hashes the pointer value. https://en.cppreference.com/w/cpp/utility/hash even calls out that `std::hash<const char*>` isn't specialized. This is fine if that's the intention, but in that case it's less confusion if you use `const void*`.

Please let me know how else I can help.

**Comment by gorcha** [comment]
Hi @michaelquinn32, thanks for the report!

This is odd - the current use of `std::unordered_map<const char*, T>` in haven seems to compare the string rather than the pointer. The map stores references for stringref variables when writing the header for a Stata file (where each record stores a reference to a string table rather than the full string value), and is then used to look up these string references later on in the code, which presumably would cause issues if it were comparing the pointer value in line with the documented `std::hash<const char*>` behaviour.

I'll have a poke around and see what's going on.

**Comment by gorcha** [comment]
After looking a bit more closely - R internally uses a global string pool, so all matching string values share the same pointer and hashing the pointer works in the map key!

**Comment by michaelquinn32** [comment]
Thanks for the fix Danny!
