### ISSUE TITLE
Trying to understand if acceptance criteria for sas7bdat unit test is correct

### ISSUE THREAD

**Issue by scottporter** [tidyverse/haven#692]
I have to deal with SAS datasets, and I tend to import them into R using `haven`.

Recently I also needed to export to SAS, which I did using `foreign`.  I decided to make sure that I could correctly round trip the data, which caused me to take a deeper look at the unit tests in `haven`.

The following unit test from `haven` doesn't seem correct to me, but perhaps I just don't understand.

```
  # converted to same time in UTC
  x2 <- as.POSIXct("2010-01-01 09:00", tz = "Pacific/Auckland")
  testthat::expect_equal(
    roundtrip_var(x2, "sas"),
    as.POSIXct("2010-01-01 09:00", tz = "UTC")
  )
```

SAS displays datetimes in the local timezone, but it stores them all in UTC.  If we have a datetime in R that is in another timezone, I don't understand why we wouldn't want it converted to the appropriate UTC time.  Even though SAS doesn't store the timezone in the file, it does assume UTC, so I think we'd want to do the same.

Perhaps this doesn't matter, since I'll not be using `haven` to write out my sas files, but I thought it was worth at least checking that this unit test isn't mistaken in it's acceptance criteria.

**Comment by gorcha** [comment]
Hi @scottporter, thanks for the feedback! This is an intentional choice (see #555) intended to give the same date time value in the output file (sans time zone) as the user sees it in R, as in our experience this is usually the user's intention.

If the converted UTC equivalent is used then the date time vector should be converted to UTC prior to writing.
