### ISSUE TITLE
read_sav default is to NOT encode user defined data

### ISSUE THREAD

**Issue by tk27182** [tidyverse/haven#749]
When I load a dataset given to me from someone who made it using SPSS, and they encode certain negative values as different reasons for the value missing, I'd expect that those negative values to be shown by default. However, all those values are NA! After looking it up, I needed to set `user_na = TRUE`. Why is `FALSE` the default value for this argument? It seems setting it to `TRUE` is more intuitive.

**Comment by gorcha** [comment]
Hi @tk27182,

I believe this default was initially used because it was assumed that missing data would generally be removed straight away after loading for data analysis, and that this was the most intuitive default for simple use.

Agree that this is not necessarily in line with general usage though! Changing the default would be a breaking change so there are no plans to do this at the moment, but it is something I'm considering for a future major release.

Thanks for the feedback!
